export const AUTH = "AUTH"
export const LOGOUT = "LOGOUT"

export const FETCH_ALL_USERS = "FETCH_USERS"
export const FETCH_USER = "FETCH_USER"
export const FETCH_EMAIL_USER = "FETCH_EMAIL_USER"
export const UPDATE_USER = "UPDATE_USER"

export const POST_CAMPAIGN = "POST_CAMPAIGN"
export const FETCH_MY_CAMPAIGN = "FETCH_MY_CAMPAIGN"

export const FETCH_ALL_CAMPAIGNS = "FETCH_ALL_CAMPAIGNS"
export const COUNT_DOWNLOADER = "COUNT_DOWNLOADER"
export const SEARCH_CAMPAIGNS = "SEARCH_CAMPAIGNS"
export const FETCH_CAMPAIGN = "FETCH_CAMPAIGN"
export const UPDATE_CAMPAIGN = "UPDATE_CAMPAIGN"
export const DELETE_CAMPAIGN = "DELETE_CAMPAIGN"
export const UPDATE_IMAGE_CAMPAIGN = "UPDATE_IMAGE_CAMPAIGN"